name: terraform-plan-slack-action
description: Creates a slack message with a summary of changes from `terraform plan`.
author: DREST LTD
inputs:
  webhook-url:
    description: Slack webhook URL.
    required: true
  channel:
    description: Slack channel.
    required: true
  name:
    description: The name of the artifact containing the output of `terraform plan`.
    required: false
    default: terraform-plan
  path:
    description: A path glob to check for `terraform plan` output files.
    required: false
  plan:
    description: The output of `terraform plan`.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
